export const PERSONALITY_QUESTIONS = [
  { id: 1, text: 'I prefer working independently over collaborating with others.' },
  { id: 2, text: 'I pay close attention to small details in my work.' },
  { id: 3, text: 'I enjoy brainstorming creative solutions to problems.' },
  { id: 4, text: 'I prefer following structured processes over improvising.' },
  { id: 5, text: 'I feel comfortable leading team discussions.' },
  { id: 6, text: 'I double-check my work before submitting it.' },
  { id: 7, text: 'I like exploring new technologies and approaches.' },
  { id: 8, text: 'I prefer having clear deadlines and milestones.' },
  { id: 9, text: 'I enjoy mentoring or helping less experienced team members.' },
  { id: 10, text: 'I find it easy to spot errors in code or documents.' },
  { id: 11, text: 'I enjoy designing user interfaces and experiences.' },
  { id: 12, text: 'I prefer working on one task at a time rather than multitasking.' },
  { id: 13, text: 'I am comfortable presenting my work to others.' },
  { id: 14, text: 'I enjoy writing documentation and technical specs.' },
  { id: 15, text: 'I like solving complex algorithmic challenges.' },
  { id: 16, text: 'I adapt quickly when project requirements change.' },
  { id: 17, text: 'I prefer async communication over real-time meetings.' },
  { id: 18, text: 'I enjoy optimizing and refactoring existing code.' },
  { id: 19, text: 'I prefer working on frontend over backend tasks.' },
  { id: 20, text: 'I thrive under pressure and tight deadlines.' },
];

export const AVAILABLE_SKILLS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue.js',
  'Angular',
  'Node.js',
  'Express',
  'Python',
  'Django',
  'Flask',
  'Java',
  'Spring',
  'Go',
  'Rust',
  'PostgreSQL',
  'MongoDB',
  'MySQL',
  'Redis',
  'GraphQL',
  'REST API',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'Git',
  'CI/CD',
  'Testing',
  'CSS',
  'Tailwind',
  'Figma',
  'UI/UX',
  'Mobile Development',
  'React Native',
];

export const TIMEZONES = [
  'UTC-12',
  'UTC-11',
  'UTC-10',
  'UTC-9',
  'UTC-8',
  'UTC-7',
  'UTC-6',
  'UTC-5',
  'UTC-4',
  'UTC-3',
  'UTC-2',
  'UTC-1',
  'UTC+0',
  'UTC+1',
  'UTC+2',
  'UTC+3',
  'UTC+4',
  'UTC+5',
  'UTC+6',
  'UTC+7',
  'UTC+8',
  'UTC+9',
  'UTC+10',
  'UTC+11',
  'UTC+12',
];
